<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__6gP3vvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..6gP3vv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..6gP3vv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eleve' => ['privates', '.errored..service_locator..6gP3vv.App\\Entity\\Eleve', NULL, 'Cannot autowire service ".service_locator..6gP3vv": it needs an instance of "App\\Entity\\Eleve" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'eleve' => 'App\\Entity\\Eleve',
            'entityManager' => '?',
        ]);
    }
}
