<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jd0PfRnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jd0PfRn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jd0PfRn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professeur' => ['privates', '.errored..service_locator.jd0PfRn.App\\Entity\\Professeur', NULL, 'Cannot autowire service ".service_locator.jd0PfRn": it needs an instance of "App\\Entity\\Professeur" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'professeur' => 'App\\Entity\\Professeur',
            'entityManager' => '?',
        ]);
    }
}
