<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XbNuJxoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XbNuJxo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XbNuJxo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professionnel' => ['privates', '.errored..service_locator.XbNuJxo.App\\Entity\\Professionnel', NULL, 'Cannot autowire service ".service_locator.XbNuJxo": it needs an instance of "App\\Entity\\Professionnel" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'professionnel' => 'App\\Entity\\Professionnel',
            'entityManager' => '?',
        ]);
    }
}
