<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cPqGpIn.App\Controller\CompteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cPqGpIn.App\\Controller\\CompteController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compteRepository' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService', true],
        ], [
            'compteRepository' => 'App\\Repository\\CompteRepository',
        ]))->withContext('App\\Controller\\CompteController::index()', $container);
    }
}
