<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iE7enwl.App\Controller\CompteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iE7enwl.App\\Controller\\CompteController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compte' => ['privates', '.errored..service_locator.iE7enwl.App\\Entity\\Compte', NULL, 'Cannot autowire service ".service_locator.iE7enwl": it needs an instance of "App\\Entity\\Compte" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'compte' => 'App\\Entity\\Compte',
            'entityManager' => '?',
            'userPasswordHasher' => '?',
        ]))->withContext('App\\Controller\\CompteController::edit()', $container);
    }
}
