<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ew.6C8e.App\Entity\Compte' shared service.
     *
     * @return \App\Entity\Compte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Ew.6C8e": it needs an instance of "App\\Entity\\Compte" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
