<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EdELPbA.App\Controller\CoursController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EdELPbA.App\\Controller\\CoursController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
        ], [
            'coursRepository' => 'App\\Repository\\CoursRepository',
        ]))->withContext('App\\Controller\\CoursController::index()', $container);
    }
}
