<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z4IG6Da.App\Controller\CompteController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z4IG6Da.App\\Controller\\CompteController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eleveRepo' => ['privates', 'App\\Repository\\EleveRepository', 'getEleveRepositoryService', true],
            'inscriptionRepo' => ['privates', 'App\\Repository\\InscriptionRepository', 'getInscriptionRepositoryService', true],
        ], [
            'eleveRepo' => 'App\\Repository\\EleveRepository',
            'inscriptionRepo' => 'App\\Repository\\InscriptionRepository',
        ]))->withContext('App\\Controller\\CompteController::show()', $container);
    }
}
