<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEleveControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.61eAldK.App\Controller\EleveController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.61eAldK.App\\Controller\\EleveController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eleve' => ['privates', '.errored..service_locator.61eAldK.App\\Entity\\Eleve', NULL, 'Cannot autowire service ".service_locator.61eAldK": it needs an instance of "App\\Entity\\Eleve" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'eleve' => 'App\\Entity\\Eleve',
        ]))->withContext('App\\Controller\\EleveController::show()', $container);
    }
}
