<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfessionnelControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oqwsgu5.App\Controller\ProfessionnelController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oqwsgu5.App\\Controller\\ProfessionnelController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professionnelRepository' => ['privates', 'App\\Repository\\ProfessionnelRepository', 'getProfessionnelRepositoryService', true],
        ], [
            'professionnelRepository' => 'App\\Repository\\ProfessionnelRepository',
        ]))->withContext('App\\Controller\\ProfessionnelController::index()', $container);
    }
}
