<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfesseurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jd0PfRn.App\Entity\Professeur' shared service.
     *
     * @return \App\Entity\Professeur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jd0PfRn": it needs an instance of "App\\Entity\\Professeur" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
