<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfessionnelControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XbNuJxo.App\Controller\ProfessionnelController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XbNuJxo.App\\Controller\\ProfessionnelController::delete()'] = ($container->privates['.service_locator.XbNuJxo'] ?? $container->load('get_ServiceLocator_XbNuJxoService'))->withContext('App\\Controller\\ProfessionnelController::delete()', $container);
    }
}
