<?php

namespace Container3TRFuiK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfessionnelControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lud1mKX.App\Controller\ProfessionnelController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lud1mKX.App\\Controller\\ProfessionnelController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professionnel' => ['privates', '.errored..service_locator.Lud1mKX.App\\Entity\\Professionnel', NULL, 'Cannot autowire service ".service_locator.Lud1mKX": it needs an instance of "App\\Entity\\Professionnel" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'professionnel' => 'App\\Entity\\Professionnel',
        ]))->withContext('App\\Controller\\ProfessionnelController::show()', $container);
    }
}
