<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccueilControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jUn2p7E.App\Controller\AccueilController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jUn2p7E.App\\Controller\\AccueilController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'typeInstrumentRepository' => ['privates', 'App\\Repository\\TypeInstrumentRepository', 'getTypeInstrumentRepositoryService', true],
        ], [
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'typeInstrumentRepository' => 'App\\Repository\\TypeInstrumentRepository',
        ]))->withContext('App\\Controller\\AccueilController::index()', $container);
    }
}
