<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6v25GEB.App\Controller\CompteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6v25GEB.App\\Controller\\CompteController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compte' => ['privates', '.errored..service_locator.6v25GEB.App\\Entity\\Compte', NULL, 'Cannot autowire service ".service_locator.6v25GEB": it needs an instance of "App\\Entity\\Compte" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userPasswordHasher' => ['privates', '.errored.St9cVbL', NULL, 'Cannot determine controller argument for "App\\Controller\\CompteController::edit()": the $userPasswordHasher argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordHasherInterface". Did you forget to add a use statement?'],
        ], [
            'compte' => 'App\\Entity\\Compte',
            'entityManager' => '?',
            'userPasswordHasher' => '?',
        ]))->withContext('App\\Controller\\CompteController::edit()', $container);
    }
}
