<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.REroOrJ.App\Controller\CoursController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.REroOrJ.App\\Controller\\CoursController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cour' => ['privates', '.errored..service_locator.REroOrJ.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.REroOrJ": it needs an instance of "App\\Entity\\Cours" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'cour' => 'App\\Entity\\Cours',
        ]))->withContext('App\\Controller\\CoursController::show()', $container);
    }
}
