<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEleve2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.61eAldK.App\Entity\Eleve' shared service.
     *
     * @return \App\Entity\Eleve
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.61eAldK": it needs an instance of "App\\Entity\\Eleve" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
