<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEleveControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..6gP3vv.App\Controller\EleveController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..6gP3vv.App\\Controller\\EleveController::delete()'] = ($container->privates['.service_locator..6gP3vv'] ?? $container->load('get_ServiceLocator__6gP3vvService'))->withContext('App\\Controller\\EleveController::delete()', $container);
    }
}
