<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEleveControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..6gP3vv.App\Controller\EleveController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator..6gP3vv'] ?? $container->load('get_ServiceLocator__6gP3vvService'));

        if (isset($container->privates['.service_locator..6gP3vv.App\\Controller\\EleveController::edit()'])) {
            return $container->privates['.service_locator..6gP3vv.App\\Controller\\EleveController::edit()'];
        }

        return $container->privates['.service_locator..6gP3vv.App\\Controller\\EleveController::edit()'] = $a->withContext('App\\Controller\\EleveController::edit()', $container);
    }
}
