<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfesseurControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jd0PfRn.App\Controller\ProfesseurController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jd0PfRn.App\\Controller\\ProfesseurController::delete()'] = ($container->privates['.service_locator.jd0PfRn'] ?? $container->load('get_ServiceLocator_Jd0PfRnService'))->withContext('App\\Controller\\ProfesseurController::delete()', $container);
    }
}
