<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfesseurControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m7qyalN.App\Controller\ProfesseurController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m7qyalN.App\\Controller\\ProfesseurController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professeur' => ['privates', '.errored..service_locator.m7qyalN.App\\Entity\\Professeur', NULL, 'Cannot autowire service ".service_locator.m7qyalN": it needs an instance of "App\\Entity\\Professeur" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'professeur' => 'App\\Entity\\Professeur',
        ]))->withContext('App\\Controller\\ProfesseurController::show()', $container);
    }
}
