<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfesseurControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jd0PfRn.App\Controller\ProfesseurController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.jd0PfRn'] ?? $container->load('get_ServiceLocator_Jd0PfRnService'));

        if (isset($container->privates['.service_locator.jd0PfRn.App\\Controller\\ProfesseurController::edit()'])) {
            return $container->privates['.service_locator.jd0PfRn.App\\Controller\\ProfesseurController::edit()'];
        }

        return $container->privates['.service_locator.jd0PfRn.App\\Controller\\ProfesseurController::edit()'] = $a->withContext('App\\Controller\\ProfesseurController::edit()', $container);
    }
}
