<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfesseurControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lJRtONh.App\Controller\ProfesseurController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lJRtONh.App\\Controller\\ProfesseurController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'professeurRepository' => ['privates', 'App\\Repository\\ProfesseurRepository', 'getProfesseurRepositoryService', true],
        ], [
            'professeurRepository' => 'App\\Repository\\ProfesseurRepository',
        ]))->withContext('App\\Controller\\ProfesseurController::index()', $container);
    }
}
