<?php

namespace ContainerG25dxoJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfessionnelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Lud1mKX.App\Entity\Professionnel' shared service.
     *
     * @return \App\Entity\Professionnel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Lud1mKX": it needs an instance of "App\\Entity\\Professionnel" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
