<?php

namespace ContainerVBwUZdD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.REroOrJ.App\Controller\CoursController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.REroOrJ.App\\Controller\\CoursController::show()'] = ($container->privates['.service_locator.REroOrJ'] ?? $container->load('get_ServiceLocator_REroOrJService'))->withContext('App\\Controller\\CoursController::show()', $container);
    }
}
