<?php

namespace ContainerVBwUZdD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mGUuBR5.App\Controller\CoursController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mGUuBR5.App\\Controller\\CoursController::delete()'] = ($container->privates['.service_locator.mGUuBR5'] ?? $container->load('get_ServiceLocator_MGUuBR5Service'))->withContext('App\\Controller\\CoursController::delete()', $container);
    }
}
