<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \App\Entity\Cours implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'ageMaxi' => [parent::class, 'ageMaxi', null, 16],
        "\0".parent::class."\0".'ageMini' => [parent::class, 'ageMini', null, 16],
        "\0".parent::class."\0".'heureDebut' => [parent::class, 'heureDebut', null, 16],
        "\0".parent::class."\0".'heureFin' => [parent::class, 'heureFin', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'inscription' => [parent::class, 'inscription', null, 16],
        "\0".parent::class."\0".'jour' => [parent::class, 'jour', null, 16],
        "\0".parent::class."\0".'libelle' => [parent::class, 'libelle', null, 16],
        "\0".parent::class."\0".'nbPlaces' => [parent::class, 'nbPlaces', null, 16],
        "\0".parent::class."\0".'professeur' => [parent::class, 'professeur', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'typeInstrument' => [parent::class, 'typeInstrument', null, 16],
        'ageMaxi' => [parent::class, 'ageMaxi', null, 16],
        'ageMini' => [parent::class, 'ageMini', null, 16],
        'heureDebut' => [parent::class, 'heureDebut', null, 16],
        'heureFin' => [parent::class, 'heureFin', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'inscription' => [parent::class, 'inscription', null, 16],
        'jour' => [parent::class, 'jour', null, 16],
        'libelle' => [parent::class, 'libelle', null, 16],
        'nbPlaces' => [parent::class, 'nbPlaces', null, 16],
        'professeur' => [parent::class, 'professeur', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'typeInstrument' => [parent::class, 'typeInstrument', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
