<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tranche extends \App\Entity\Tranche implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'eleves' => [parent::class, 'eleves', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'libelle' => [parent::class, 'libelle', null, 16],
        "\0".parent::class."\0".'quotientMini' => [parent::class, 'quotientMini', null, 16],
        "\0".parent::class."\0".'responsable' => [parent::class, 'responsable', null, 16],
        "\0".parent::class."\0".'tarifs' => [parent::class, 'tarifs', null, 16],
        'eleves' => [parent::class, 'eleves', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'libelle' => [parent::class, 'libelle', null, 16],
        'quotientMini' => [parent::class, 'quotientMini', null, 16],
        'responsable' => [parent::class, 'responsable', null, 16],
        'tarifs' => [parent::class, 'tarifs', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
